version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: crm-laravel
    environment:
      MYSQL_DATABASE: crm
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
